// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class RubikscubeTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void rubikscube() {
    driver.Navigate().GoToUrl("https://www.google.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(652, 672);
    driver.FindElement(By.Id("APjFqb")).SendKeys("rubik\'s cube");
    js.ExecuteScript("window.scrollTo(0,172.1212158203125)");
    js.ExecuteScript("window.scrollTo(0,190.90908813476562)");
    js.ExecuteScript("window.scrollTo(0,406.66668701171875)");
    js.ExecuteScript("window.scrollTo(0,405.4545593261719)");
  }
}
